name: Build_Flux_Folding@Home_ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=false" \
            --tag runonflux/folding-at-home:1.1 --file Dockerfile .
      - name: Docker Push
        run: |
          docker push runonflux/folding-at-home
